### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jonschlinkert** [begin/templating#1]
Create the definitive guide to templating!!!

- [ ] detailed outline - let's start by creating an outline for us to use in creating the guide
- [ ] blog post - once the guide is complete enough to share, publish a blog post to announce it and explain why we created the guide

**Ideas for guide sections**

- [x] table of contents
- [x] introduction: what is templating? why is it useful? What to expect from the guide, etc. 
- [x] templating terminology
- [ ] template features and concepts
- [ ] template syntaxes and languages, and how they work
- [ ] template engines
- [ ] examples and comparisons of implementations
- [ ] additional reading, related resources
